name: frontend-ci-cd
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем всю историю для проверки изменений

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Кэшируем node_modules для ускорения
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps (clean)
        run: npm ci

      # Проверяем изменения в тестовых файлах
      - name: Check test files changes
        id: check-test-changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Для PR сравниваем с базовой веткой
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            # Для push сравниваем с предыдущим коммитом
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.event.after }}"
          fi
          
          # Проверяем изменения в тестовых файлах
          TEST_CHANGES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E '\.(spec|test)\.(ts|js)$|e2e/|test/' | wc -l)
          
          # Проверяем изменения в основных файлах (если есть изменения в src, то нужны тесты)
          SRC_CHANGES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E '^src/' | grep -v -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          echo "test-changes=$TEST_CHANGES" >> $GITHUB_OUTPUT
          echo "src-changes=$SRC_CHANGES" >> $GITHUB_OUTPUT
          echo "run-tests=$([ $SRC_CHANGES -gt 0 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          
          echo "🔍 Test files changed: $TEST_CHANGES"
          echo "🔍 Source files changed: $SRC_CHANGES"
          echo "🔍 Will run tests: $([ $SRC_CHANGES -gt 0 ] && echo 'YES' || echo 'NO')"

      # Quality gates (блокирующие) - исключаем указанные папки
      - name: Lint (ESLint/Prettier) - exclude specified folders
        run: npm run lint:ci

      - name: Unit tests (Jasmine/Karma) - exclude specified folders  
        if: steps.check-test-changes.outputs.run-tests == 'true'
        run: npm run test:ci

      - name: Skip unit tests - no source changes
        if: steps.check-test-changes.outputs.run-tests == 'false'
        run: echo "⏭️ Skipping unit tests - no source code changes detected"

      # Проверяем нужны ли E2E тесты
      - name: Check E2E test requirements
        id: check-e2e-changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.event.after }}"
          fi
          
          # Проверяем изменения в E2E тестах или критических файлах
          E2E_CHANGES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E 'e2e/|playwright|\.github/workflows/' | wc -l)
          
          # Проверяем изменения в основных компонентах (требуют E2E)
          CRITICAL_CHANGES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E 'src/app/(auth|features|shared)/' | grep -v -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          echo "e2e-changes=$E2E_CHANGES" >> $GITHUB_OUTPUT
          echo "critical-changes=$CRITICAL_CHANGES" >> $GITHUB_OUTPUT
          echo "run-e2e=$([ $E2E_CHANGES -gt 0 -o $CRITICAL_CHANGES -gt 0 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          
          echo "🔍 E2E files changed: $E2E_CHANGES"
          echo "🔍 Critical components changed: $CRITICAL_CHANGES"
          echo "🔍 Will run E2E tests: $([ $E2E_CHANGES -gt 0 -o $CRITICAL_CHANGES -gt 0 ] && echo 'YES' || echo 'NO')"

      - name: Install Playwright (browsers)
        if: steps.check-e2e-changes.outputs.run-e2e == 'true'
        run: npx playwright install --with-deps

      - name: Remove excluded directories before E2E and build
        if: steps.check-e2e-changes.outputs.run-e2e == 'true'
        run: |
          # Удаляем папки перед E2E тестами и билдом для production
          rm -rf public/
          rm -rf src/app/classroom/lesson-material/tabs/
          rm -rf src/app/features/landing/
          rm -rf src/app/features/marathons/
          rm -rf src/app/features/materials/
          rm -rf src/app/features/tariffs/
          rm -rf src/app/features/users/
          rm -rf src/app/shared/components/schedule/
          rm -rf src/app/test-video-call/

      - name: E2E tests (Playwright headless)
        if: steps.check-e2e-changes.outputs.run-e2e == 'true'
        run: npm run e2e

      - name: Skip E2E tests - no critical changes
        if: steps.check-e2e-changes.outputs.run-e2e == 'false'
        run: echo "⏭️ Skipping E2E tests - no critical changes detected"

      # Кэшируем Angular build для ускорения
      - name: Cache Angular build
        uses: actions/cache@v3
        with:
          path: |
            .angular/cache
            dist/
          key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json', '**/angular.json', '**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-angular-

      - name: Build (Angular prod w/ budgets)
        run: npm run build --configuration=production

      - name: Create filtered build artifact (exclude specified folders)
        run: |
          # Создаем временную папку для фильтрованного билда
          mkdir -p filtered-dist
          
          # Копируем всё, кроме исключенных папок
          rsync -av \
            --exclude="**/tabs/" \
            --exclude="**/landing/" \
            --exclude="**/marathons/" \
            --exclude="**/materials/" \
            --exclude="**/tariffs/" \
            --exclude="**/calendar/" \
            --exclude="**/schedule/" \
            --exclude="**/test-video-call/" \
            --exclude="public/" \
            dist/**/browser/ filtered-dist/

      - name: Upload build artifact (without excluded folders)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: filtered-dist/

      - name: Deploy to OVH via rsync (only master) - with exclusions
        if: github.ref == 'refs/heads/master'
        env:
          OVH_HOST: ${{ secrets.OVH_HOST }}
          OVH_USER: ${{ secrets.OVH_USER }}
          SSH_KEY:  ${{ secrets.OVH_SSH_KEY }}
          REMOTE_DIR: /www/wwwroot/135.125.107.45
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          ssh-keyscan -p "${OVH_PORT:-22}" "$OVH_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Отладка SSH ключа
          echo "=== SSH Key Debug ==="
          echo "SSH key file exists: $(test -f ~/.ssh/id_deploy && echo 'YES' || echo 'NO')"
          echo "SSH key permissions: $(ls -la ~/.ssh/id_deploy)"
          echo "SSH key content (first 50 chars): $(head -c 50 ~/.ssh/id_deploy)"
          echo "SSH key type: $(head -c 20 ~/.ssh/id_deploy)"
          echo "===================="
          
          # Проверяем SSH подключение с подробной отладкой
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_deploy -p "${OVH_PORT:-22}" -o ConnectTimeout=10 -o StrictHostKeyChecking=no -v "${OVH_USER}@${OVH_HOST}" "echo 'SSH connection successful'" 2>&1 || echo "SSH connection failed"
          
          # Деплоим отфильтрованную сборку (исключенные папки уже удалены)
          rsync -avz \
          --delete \
          --exclude='.user.ini' \
          --no-perms --omit-dir-times \
          -e "ssh -i ~/.ssh/id_deploy -p ${OVH_PORT:-22}" \
          filtered-dist/ "${OVH_USER}@${OVH_HOST}:${REMOTE_DIR}/"
            
          # если менял конфиг, перезагрузи Nginx
          ssh -i ~/.ssh/id_deploy -p "${OVH_PORT:-22}" "${OVH_USER}@${OVH_HOST}" \
            "sudo nginx -t && sudo systemctl reload nginx || true"
