name: frontend-ci-cd
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем всю историю для проверки изменений

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Кэшируем node_modules для ускорения
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps (clean)
        run: npm ci

      # Проверяем изменения для всех типов тестов
      - name: Check all test requirements
        id: check-all-tests
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Для PR сравниваем с базовой веткой
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            # Для push сравниваем с предыдущим коммитом
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.event.after }}"
          fi
          
          # Получаем список всех измененных файлов
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
          
          # Проверяем изменения в Unit тестах
          UNIT_TEST_CHANGES=$(echo "$CHANGED_FILES" | grep -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          # Проверяем изменения в E2E тестах
          E2E_TEST_CHANGES=$(echo "$CHANGED_FILES" | grep -E 'e2e/|playwright|\.github/workflows/' | wc -l)
          
          # Проверяем изменения в основных файлах (требуют unit тестов)
          SRC_CHANGES=$(echo "$CHANGED_FILES" | grep -E '^src/' | grep -v -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          # Проверяем изменения в критичных компонентах (требуют E2E)
          CRITICAL_CHANGES=$(echo "$CHANGED_FILES" | grep -E 'src/app/(auth|features|shared)/' | grep -v -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          # Проверяем изменения в конфигурации тестов
          TEST_CONFIG_CHANGES=$(echo "$CHANGED_FILES" | grep -E '(karma|jasmine|test|spec|playwright|jest)\.(json|js|ts|conf)$|\.github/workflows/' | wc -l)
          
          # Проверяем изменения в интеграционных тестах (если есть)
          INTEGRATION_TEST_CHANGES=$(echo "$CHANGED_FILES" | grep -E '(integration|api|service).*\.(spec|test)\.(ts|js)$' | wc -l)
          
          # Проверяем изменения в сервисах (требуют интеграционных тестов)
          SERVICE_CHANGES=$(echo "$CHANGED_FILES" | grep -E 'src/app/services/' | grep -v -E '\.(spec|test)\.(ts|js)$' | wc -l)
          
          # Логика запуска тестов
          RUN_UNIT_TESTS=$([ $SRC_CHANGES -gt 0 -o $UNIT_TEST_CHANGES -gt 0 -o $TEST_CONFIG_CHANGES -gt 0 ] && echo 'true' || echo 'false')
          RUN_E2E_TESTS=$([ $E2E_TEST_CHANGES -gt 0 -o $CRITICAL_CHANGES -gt 0 -o $TEST_CONFIG_CHANGES -gt 0 ] && echo 'true' || echo 'false')
          RUN_INTEGRATION_TESTS=$([ $INTEGRATION_TEST_CHANGES -gt 0 -o $SERVICE_CHANGES -gt 0 -o $TEST_CONFIG_CHANGES -gt 0 ] && echo 'true' || echo 'false')
          
          # Выводим результаты
          echo "unit-test-changes=$UNIT_TEST_CHANGES" >> $GITHUB_OUTPUT
          echo "e2e-test-changes=$E2E_TEST_CHANGES" >> $GITHUB_OUTPUT
          echo "integration-test-changes=$INTEGRATION_TEST_CHANGES" >> $GITHUB_OUTPUT
          echo "src-changes=$SRC_CHANGES" >> $GITHUB_OUTPUT
          echo "critical-changes=$CRITICAL_CHANGES" >> $GITHUB_OUTPUT
          echo "service-changes=$SERVICE_CHANGES" >> $GITHUB_OUTPUT
          echo "test-config-changes=$TEST_CONFIG_CHANGES" >> $GITHUB_OUTPUT
          echo "run-unit-tests=$RUN_UNIT_TESTS" >> $GITHUB_OUTPUT
          echo "run-e2e-tests=$RUN_E2E_TESTS" >> $GITHUB_OUTPUT
          echo "run-integration-tests=$RUN_INTEGRATION_TESTS" >> $GITHUB_OUTPUT
          
          echo "🔍 === АНАЛИЗ ИЗМЕНЕНИЙ ==="
          echo "📝 Unit test files changed: $UNIT_TEST_CHANGES"
          echo "🎭 E2E test files changed: $E2E_TEST_CHANGES"
          echo "🔗 Integration test files changed: $INTEGRATION_TEST_CHANGES"
          echo "📁 Source files changed: $SRC_CHANGES"
          echo "⚡ Critical components changed: $CRITICAL_CHANGES"
          echo "🔧 Service files changed: $SERVICE_CHANGES"
          echo "⚙️ Test config files changed: $TEST_CONFIG_CHANGES"
          echo ""
          echo "🚀 === РЕШЕНИЕ ==="
          echo "🧪 Unit tests: $([ $RUN_UNIT_TESTS = 'true' ] && echo 'RUN' || echo 'SKIP')"
          echo "🎭 E2E tests: $([ $RUN_E2E_TESTS = 'true' ] && echo 'RUN' || echo 'SKIP')"
          echo "🔗 Integration tests: $([ $RUN_INTEGRATION_TESTS = 'true' ] && echo 'RUN' || echo 'SKIP')"
          echo "========================"

      # Quality gates (блокирующие) - исключаем указанные папки
      - name: Lint (ESLint/Prettier) - exclude specified folders
        run: npm run lint:ci

      - name: Unit tests (Jasmine/Karma) - exclude specified folders  
        if: steps.check-all-tests.outputs.run-unit-tests == 'true'
        run: npm run test:ci

      - name: Skip unit tests - no relevant changes
        if: steps.check-all-tests.outputs.run-unit-tests == 'false'
        run: echo "⏭️ Skipping unit tests - no source code or test changes detected"

      # Интеграционные тесты (если есть в проекте)
      - name: Integration tests (if configured)
        if: steps.check-all-tests.outputs.run-integration-tests == 'true'
        run: |
          if npm run test:integration --if-present; then
            echo "✅ Integration tests passed"
          else
            echo "ℹ️ No integration tests configured"
          fi

      - name: Skip integration tests - no service changes
        if: steps.check-all-tests.outputs.run-integration-tests == 'false'
        run: echo "⏭️ Skipping integration tests - no service files or integration test changes detected"

      # E2E тесты с умной установкой Playwright
      - name: Install Playwright (browsers) - only when needed
        if: steps.check-all-tests.outputs.run-e2e-tests == 'true'
        run: |
          echo "🎭 Installing Playwright browsers for E2E tests..."
          npx playwright install --with-deps
          echo "✅ Playwright installation completed"

      - name: Prepare E2E environment
        if: steps.check-all-tests.outputs.run-e2e-tests == 'true'
        run: |
          echo "🧹 Cleaning excluded directories for E2E tests..."
          # Удаляем папки перед E2E тестами и билдом для production
          rm -rf public/
          rm -rf src/app/classroom/lesson-material/tabs/
          rm -rf src/app/features/landing/
          rm -rf src/app/features/marathons/
          rm -rf src/app/features/materials/
          rm -rf src/app/features/tariffs/
          rm -rf src/app/features/users/
          rm -rf src/app/shared/components/schedule/
          rm -rf src/app/test-video-call/
          echo "✅ Environment prepared for E2E tests"

      - name: E2E tests (Playwright headless)
        if: steps.check-all-tests.outputs.run-e2e-tests == 'true'
        run: |
          echo "🎭 Running E2E tests..."
          npm run e2e
          echo "✅ E2E tests completed"

      - name: Skip E2E tests - no relevant changes
        if: steps.check-all-tests.outputs.run-e2e-tests == 'false'
        run: echo "⏭️ Skipping E2E tests - no E2E files, critical components or test config changes detected"

      # Кэшируем Angular build для ускорения
      - name: Cache Angular build
        uses: actions/cache@v3
        with:
          path: |
            .angular/cache
            dist/
          key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json', '**/angular.json', '**/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-angular-

      - name: Build (Angular prod w/ budgets)
        run: npm run build --configuration=production

      - name: Create filtered build artifact (exclude specified folders)
        run: |
          # Создаем временную папку для фильтрованного билда
          mkdir -p filtered-dist
          
          # Копируем всё, кроме исключенных папок
          rsync -av \
            --exclude="**/tabs/" \
            --exclude="**/landing/" \
            --exclude="**/marathons/" \
            --exclude="**/materials/" \
            --exclude="**/tariffs/" \
            --exclude="**/calendar/" \
            --exclude="**/schedule/" \
            --exclude="**/test-video-call/" \
            --exclude="public/" \
            dist/**/browser/ filtered-dist/

      - name: Upload build artifact (without excluded folders)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: filtered-dist/

      - name: Deploy to OVH via rsync (only master) - with exclusions
        if: github.ref == 'refs/heads/master'
        env:
          OVH_HOST: ${{ secrets.OVH_HOST }}
          OVH_USER: ${{ secrets.OVH_USER }}
          SSH_KEY:  ${{ secrets.OVH_SSH_KEY }}
          REMOTE_DIR: /www/wwwroot/135.125.107.45
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          ssh-keyscan -p "${OVH_PORT:-22}" "$OVH_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Отладка SSH ключа
          echo "=== SSH Key Debug ==="
          echo "SSH key file exists: $(test -f ~/.ssh/id_deploy && echo 'YES' || echo 'NO')"
          echo "SSH key permissions: $(ls -la ~/.ssh/id_deploy)"
          echo "SSH key content (first 50 chars): $(head -c 50 ~/.ssh/id_deploy)"
          echo "SSH key type: $(head -c 20 ~/.ssh/id_deploy)"
          echo "===================="
          
          # Проверяем SSH подключение с подробной отладкой
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_deploy -p "${OVH_PORT:-22}" -o ConnectTimeout=10 -o StrictHostKeyChecking=no -v "${OVH_USER}@${OVH_HOST}" "echo 'SSH connection successful'" 2>&1 || echo "SSH connection failed"
          
          # Деплоим отфильтрованную сборку (исключенные папки уже удалены)
          rsync -avz \
          --delete \
          --exclude='.user.ini' \
          --no-perms --omit-dir-times \
          -e "ssh -i ~/.ssh/id_deploy -p ${OVH_PORT:-22}" \
          filtered-dist/ "${OVH_USER}@${OVH_HOST}:${REMOTE_DIR}/"
            
          # если менял конфиг, перезагрузи Nginx
          ssh -i ~/.ssh/id_deploy -p "${OVH_PORT:-22}" "${OVH_USER}@${OVH_HOST}" \
            "sudo nginx -t && sudo systemctl reload nginx || true"
